site_name: ""

docs_dir: docs/

site_url: https://ch3ckm8.github.io/personal_blog5/
use_directory_urls: true

nav:
  - Home: index.md
  - Community:
    -  community.md
  - Contributions:
    -  contributions_mediawiki.md
  - Tags:
    - tags.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections

plugins:
  - search:
      lang: en
  - tags:
      tags_file: tags.md
  - title-casing:
      capitalization_type: title
